version: '3.8'

services:
  nest-app:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://mongo:27017/imagequeue

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
